version: "3.8"
services:
  api:
    container_name: api
    build: .
    tty: true
    command: yarn start:dev
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /api

  db:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password