version: "3.8"
services:
  api:
    container_name: api
    build: .
    tty: true
    command: sh -c "yarn start:dev"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /api
    networks:
      - smore_recipe_api

  db:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - smore_recipe_api

networks:
  smore_recipe_api:
    external: true