version: "3.8"
services:
  api:
    container_name: api
    build: .
    tty: true
    command: yarn start:dev
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /api